### ISSUE TITLE
Error: Cannot read & write on path "database.json"

### ISSUE THREAD

**Issue by dcromster** [nmaggioni/Simple-JSONdb#1]
I got this error if file with data (or null sized) already present.

**Comment by nmaggioni** [comment]
Could you show me the relevant part of your code? I'm not able to reproduce this, choosing an existing or invalid file results in the `Error: Given filePath is not empty and its content is not valid JSON.` being thrown correctly.
I suspect it is a permission problem, have you checked that you have RW permission on the specified path?

**Comment by nmaggioni** [comment]
A stacktrace would also help identifying the problem clearly.

**Comment by nmaggioni** [comment]
Closed for lack of feedback. Can be reopened anytime if more info are available!
