### ISSUE TITLE
[BUG] Key and Value is not stored in the .json file

### ISSUE THREAD

**Issue by Nigelrex** [nmaggioni/Simple-JSONdb#10]
I saw your npm and wanted to try it out and i switched from quick.db to Simple-JSONdb to check if that works, but the key and the value is NOT getting stored in the json.

**Comment by nmaggioni** [comment]
Pretty difficult to reproduce without at least a code snippet, some version numbers or a stacktrace.
All tests complete fine and work as expected on a clean install. Check your permissions, paths and logs.

**Comment by Nigelrex** [comment]
Everything is valid, there is absolutely no error in the code and the `console.log("Working ");` is executed after setting the value in the db

**Comment by nmaggioni** [comment]
Again, without at the very least a snippet of code there's nothing that can be done to troubleshoot this. Saying that a random logging statement is working has no meaning at all, you should do some research on [NodeJS's event loop](https://nodejs.org/fa/docs/guides/event-loop-timers-and-nexttick/) and how asyncronous calls work.

My best bet is that your script exits right after trying to write something on disk, and thus the async call gets terminated early.

Closing until proper reproduction steps are given.
