### ISSUE TITLE
Advanced options?

### ISSUE THREAD

**Issue by a-a-GiTHuB-a-a** [nmaggioni/Simple-JSONdb#15]
# Type: New feature
I think it would be cool if there were advanced options for the constructor. For example, custom serializers and deserializers(like `fast-json-stringify` for efficiency), etc.

Or if you don't want to add these features because this is `simple`, that's fine, too.

**Comment by nmaggioni** [comment]
Thanks for the tip, PRs are open.

**Comment by a-a-GiTHuB-a-a** [comment]
I have submitted a PR: <https://github.com/nmaggioni/Simple-JSONdb/pull/16>
Also, you forgot `jsonSpaces` in your typedefs for options, so I fixed that too!
