### ISSUE TITLE
.has() restart required?

### ISSUE THREAD

**Issue by LeonTheDev-io** [nmaggioni/Simple-JSONdb#20]
Hello there, whenever I change (set/delete) a value in the database, .has() will still return the old state, till I restart the bot
I got no clue why it does not work right, here are some snippets of my code.

**Index.js**
```js
const JSONdb = require('simple-json-db');
const db = new JSONdb('invites.json');
// . . .
client.on('guildMemberAdd',(member) => {
	if(!db.has(member.id)){
		member.ban({ reason: 'User not allowed' })
	}
	else if(db.has(member.id)){
		member.roles.add(member.guild.roles.cache.find(r => r.id === "978789500421545994"));
	}
});
// . . .
```

**Allow.js**
```js
const JSONdb = require('simple-json-db');
const db = new JSONdb('invites.json');
// . . .
async execute(interaction) {
		if(interaction.member.id === "584070402679111682"){
        db.set(interaction.options.getUser('user').id,'x')
        await interaction.reply('User added');
    }
// . . .
```

So, I run allow.js, the userid gets added to the database, but .has will still return FALSE till I restart the bot.

**Comment by nmaggioni** [comment]
This is covered by [a test case](https://github.com/nmaggioni/Simple-JSONdb/blob/1adce73d23eb0fd5fb7f9600bc7f066b6576843a/test.js#L102) which is currently passing, and under normal circumstances the [set](https://github.com/nmaggioni/Simple-JSONdb/blob/1adce73d23eb0fd5fb7f9600bc7f066b6576843a/index.js#L100) and [has](https://github.com/nmaggioni/Simple-JSONdb/blob/1adce73d23eb0fd5fb7f9600bc7f066b6576843a/index.js#L118) functions are pretty much guaranteed to succeed by the runtime. I'd suggest looking for concurrency issues in your code.
