### ISSUE TITLE
Fails to parse json in Bun

### ISSUE THREAD

**Issue by danielchoutka** [nmaggioni/Simple-JSONdb#21]
**Describe the bug**
Parsing an existing json file fails

**To Reproduce**
Steps to reproduce the behavior or a relevant snippet of code:
1. [Get bun](https://bun.sh) (0.1.4 beta, up to date)
2.`bun index.js`

```javascript
const d = [date.getDate(), date.getMonth()+1, date.getFullYear()].join("-")
const db = new JSONdb(`/home/maze/.config/lyft-counter/logs/${d}.json`)

db.set(date.getTime(), "")
```

**Expected behavior**
push `<current date>: ""` into the db file
**Environment**
 - OS: Gentoo, up to date
 - Runtime: Bun 0.1.4 (works perfectly fine with node 18)

```
> bun index.js add 
Given filePath is not empty and its content is not valid JSON.
17 |  * @param {string} fileContent
18 |  * @returns {boolean} `true` if content is ok, throws error if not.
19 |  */
20 | let validateJSON = function(fileContent) {
21 |   try {
22 |     this.options.parse(fileContent);
        ^
 SyntaxError: JSON Parse error: Unable to parse JSON string
      at validateJSON (/home/maze/code/lyft-counter/node_modules/simple-json-db/index.js:22:4)
      at new JSONdb (/home/maze/code/lyft-counter/node_modules/simple-json-db/index.js:90:8)
      at /home/maze/code/lyft-counter/index.js:7:11
```

**Comment by nmaggioni** [comment]
Please post the contents of the referenced file as well, are you sure that you don't have any spurious characters in there?

**Comment by danielchoutka** [comment]
```
{
    "key": "value"
}
```
Updated to bun 0.1.5.
There are no weird characters, it was generated by the package itself, which does work. 
Currently this is how the current testing code looks like:
```javascript
const json = require('simple-json-db');
const db = new json('db.json');

db.set('key', 'value');
```
In the first run, when no file exists it creates it just fine, on the second run I get exactly the same error message as mentioned in original issue.

**Comment by danielchoutka** [comment]
Okay, after a bit of investigation after adding `console.log(fileContent)` I have found out it's `[ 123, 34, 107, 101, 121, 34, 58, 32, 34, 118, 97, 108, 117, 101, 34, 125, 10 ]`, an array of the utf8 codes.

**Comment by nmaggioni** [comment]
To me this looks like an issue with Bun's compatibility layer, I'd suggest you to raise it on their upstream since I'm seeing a couple other JSON-related issues there already. Closing for the moment, I'll reopen if new library-specific details arise.
