### ISSUE TITLE
function Sync confused

### ISSUE THREAD

**Issue by 9a-aaaaaaaa** [nmaggioni/Simple-JSONdb#25]
Can I understand that Sync is saved as ?

**Comment by nmaggioni** [comment]
I'm sorry, I'll need way more info than that to grasp what's your issue.

**Comment by nvx0** [comment]
If I am not wrong you need an explenation what does ``<JSONDb>#sync`` do. ``<JSONDb>#sync`` is writing the modified data to file that you have specified (in this case json file). Hope that helps!
