### ISSUE TITLE
Use in another file

### ISSUE THREAD

**Issue by usertorri** [nmaggioni/Simple-JSONdb#26]
Hello. Is it possible to use the database in another file and not in the main one. Tried through require but gave an error "db.get is a not a function".
If possible, please give an example.

**Comment by nmaggioni** [comment]
Hi, I'd suggest you to take a deeper look at how requiring modules and files works in NodeJS. Here are some resources:

• https://nodejs.org/en/knowledge/getting-started/what-is-require/
• https://www.w3schools.com/nodejs/nodejs_modules.asp
• https://www.freecodecamp.org/news/requiring-modules-in-node-js-everything-you-need-to-know-e7fbd119be8/
