### ISSUE TITLE
Question: Set/Get value to/from nested keys

### ISSUE THREAD

**Issue by Valexr** [nmaggioni/Simple-JSONdb#6]
How I can set/get value to/form nested key?
Something like this:

```json
// database.json

 {
    "test": {
        "data1" : {
            "array" : "['test', 'array']"
        },
        "data2 ": 5
    }
}
```

```js
// db.js

const JSONdb = require('simple-json-db');
const db = new JSONdb('/path/to/your/database.json');

db.set('test.data1', 'id: 1');

db.get('test.data1');
```

**Comment by nmaggioni** [comment]
You can't, this is a key-value store: if you need nested properties you must get/set the whole stringified chunk. I'd suggest you to look into data storage solutions that better suit your use case.
