### ISSUE TITLE
Inserting data

### ISSUE THREAD

**Issue by fdciabdul** [nmaggioni/Simple-JSONdb#7]
when i run this code

```javascript
const get = db.set('id' , 'test')
console.log(db.get('id'));
```

it store JSON data like this

```json
{
    "id": "test"
}
```

but when i try again with different value

```javascript
const get = db.set('id' , 'test1')
console.log(db.get('id'));
```

in database.json that's not add new value , but just replaced from value before

```json
{
    "id": "test1"
}
```

i mean , when i run the code with different value , it show like this
```json
{
    "id": "test"
},
{
    "id": "test1"
}
```

**Comment by nmaggioni** [comment]
That's not how JSON works. How could you ever differentiate which key to get if you had two with the same name, for example?

**Comment by fdciabdul** [comment]
> That's not how JSON works. How could you ever differentiate which key to get if you had two with the same name, for example?

but how to create multidimensional json object with this  ?

**Comment by nmaggioni** [comment]
See #6. Wrong tool for the job.
