### ISSUE TITLE
One key/value pair gets updated by the set call of another

### ISSUE THREAD

**Issue by johanalkstal** [nmaggioni/Simple-JSONdb#9]
I'm getting some unexpected behavior and maybe there's a good explanation for it?

The premise is that I have two different key/value pairs in my database but they share similar similar data.
Both are arrays of objects.
And I've noticed that calling .set to update the first and then .set to update the second will change the data in the first.

Example:

```
const JSONdb = require('simple-json-db')

const db = new JSONdb('./db.json')

db.JSON({ "A": [{ "AA": 0 }], "B": [{ "AA": 0 }]}) // Two key/value pairs with similar objects

const A = db.get('A')

A[0].AA = 1

db.set('B', A) // Update the object and set it

A[0].AA = 2

db.set('A', A) // Update the object again and set it to a different key

console.log(db.JSON()) // { A: [ { AA: 2 } ], B: [ { AA: 2 } ] }
```

I can imagine it has something to do with object references since it is the same object being stored in both.
But I would have guessed that the call to .set() would have written the data to disk so that there is no reference left?

Or is writing to disk done in bulk? Do I need to set syncOnWrite to false?

**Comment by nmaggioni** [comment]
Storage isn't involved here, as you noticed it's just a matter of object references: you need to clone A before assigning it to B if you intend to change it, or it will always point to the same object inside the JS engine, regardless of what happens on disk in the meantime.

```javascript
const JSONdb = require('simple-json-db')

const db = new JSONdb('./db.json');
db.JSON({ "A": [{ "AA": 0 }], "B": [{ "AA": 0 }]});                                           

const A = db.get('A');
A[0].AA = 1;

//db.set('B', A);                            
db.set('B', JSON.parse(JSON.stringify(A)));  // Barebones way to clone simple objects

A[0].AA = 2;
db.set('A', A);                                                        

console.log(db.JSON());  // { A: [ { AA: 2 } ], B: [ { AA: 1 } ] }
```
